const products = [
    {id:'b1', name:'Banneton Redondo', price: 10, category: 'banneton', image: '../img/bannetones/ban-redondo.jpg', stock: 20, description:'Usar un banneton te ayudará a obtener una barra más crujiente con una corteza deliciosamente crujiente. Esto se debe a que las cestas banneton están hechas de caña natural y funcionan creando un microclima ligeramente húmedo entre la masa y el banneton durante la prueba. Como la masa se seca, crea una piel, y esto es lo que hace una corteza magnífica en el pan artesanal. ¡Disfruta de tu pan redondo crujiente con un hermoso patrón ascendente!', detail: 'Medidas aproximadas: 21x8cm'},
    {id:'b2', name:'Banneton Barra', price: 12, category: 'banneton', image: '../img/bannetones/ban-barra.jpg', stock: 25, description:'Usar un banneton te ayudará a obtener una barra más crujiente con una corteza deliciosamente crujiente. Esto se debe a que las cestas banneton están hechas de caña natural y funcionan creando un microclima ligeramente húmedo entre la masa y el banneton durante la prueba. Como la masa se seca, crea una piel, y esto es lo que hace una corteza magnífica en el pan artesanal. ¡Disfruta de tu pan redondo crujiente con un hermoso patrón ascendente!', detail: 'Medidas aproximadas: 35x10x8cm'},
    {id:'b3', name:'Banneton Cuadrado', price: 15, category: 'banneton', image: '../img/bannetones/ban-cuadrado.jpg', stock: 10, description:'Usar un banneton te ayudará a obtener una barra más crujiente con una corteza deliciosamente crujiente. Esto se debe a que las cestas banneton están hechas de caña natural y funcionan creando un microclima ligeramente húmedo entre la masa y el banneton durante la prueba. Como la masa se seca, crea una piel, y esto es lo que hace una corteza magnífica en el pan artesanal. ¡Disfruta de tu pan redondo crujiente con un hermoso patrón ascendente!', detail: 'Medidas aproximadas: 15x15x8cm'},
    {id:'b4', name:'Banneton Tiangulo', price: 13, category: 'banneton', image: '../img/bannetones/ban-triangulo.jpg', stock: 10, description:'Usar un banneton te ayudará a obtener una barra más crujiente con una corteza deliciosamente crujiente. Esto se debe a que las cestas banneton están hechas de caña natural y funcionan creando un microclima ligeramente húmedo entre la masa y el banneton durante la prueba. Como la masa se seca, crea una piel, y esto es lo que hace una corteza magnífica en el pan artesanal. ¡Disfruta de tu pan redondo crujiente con un hermoso patrón ascendente!', detail: 'Medidas aproximadas: 18x8cm'},
    {id:'b5', name:'Banneton Ovalado', price: 10, category: 'banneton', image: '../img/bannetones/ban-ovalado.jpg', stock: 30, description:'Usar un banneton te ayudará a obtener una barra más crujiente con una corteza deliciosamente crujiente. Esto se debe a que las cestas banneton están hechas de caña natural y funcionan creando un microclima ligeramente húmedo entre la masa y el banneton durante la prueba. Como la masa se seca, crea una piel, y esto es lo que hace una corteza magnífica en el pan artesanal. ¡Disfruta de tu pan redondo crujiente con un hermoso patrón ascendente!', detail: 'Medidas aproximadas: 21x15x8cm'},
    {id: 'f1', name: 'Bob Redmill - Vital Wheat Gluten', price: 97, category: 'flour', image: '../img/flour/bobredmill-vitalwheat.jpg', stock: 20, description: 'Made from the endosperm of the highest quality wheat berries, Bobs Red Mill vital wheat gluten is a versatile ingredient for a number of recipes! It contains 75% to 80% protein, making it an excellent binding agent. Try adding it to artisan breads made from coarsely ground grains to create a light, fluffy texture and a lofty crumb that will make your baked creations truly stand out.', detail: '25lb'},
    {id: 'f2', name: 'Bob Redmill - All Purpose', price: 54, category: 'flour', image: '../img/flour/bobredmill-allpurpose.jpg', stock: 30, description: "This gluten free flours fine texture makes it perfect for a wide variety of applications! It works well for creating pie and pizza crusts, pasta, pancakes and other tasty treats. It's also suitable in yeasted recipes - though you may need to adjust the levels of other ingredients when baking gluten-free bread, bagels, or pretzels. This versatile flour takes the work out of creating the perfect gluten-free flour blend for all of your baked goods, making it an ingredient that you'll reach for time and time again!", detail: '25lb'},
    {id: 'f3', name: 'King Arthur - Special Patent', price: 32, category: 'flour', image: '../img/flour/kingarthur-specialpatent.jpg', stock: 25, description: "This artisan special patent flour is a classic spring wheat bread flour that is milled from the center of the hard red spring wheat kernel, which results in a high protein, low ash flour. It works well with both hand or machine production, and provides great volume. Plus, it is never bleached nor bromated, thus eliminating the need for chemical agents as well as the risk of adding a slight chlorine taste to your foods. This flour gives you reliable results with consistently high volume and even texture that you can feel good about serving to your customers!", detail: '50lb'},
    {id: 'f4', name: 'King Arthur - Sir Galahad', price: 32, category: 'flour', image: '../img/flour/kingarthur-sirgalahad.jpg', stock: 20, description: "This artisan all-purpose flour is prepared by carefully selecting and milling premium hard red winter wheat for a low-protein bread flour that is also soft enough to make pastries, making it a versatile addition to any bakery. Since all-purpose flour is such a fundamental ingredient, it can be used in many popular dishes of different cultures and palates. This unbleached flour gives you reliable results with consistently high volume and even texture that you can feel good about serving to your customers!", detail: '50lb'},
    {id: 'f5', name: 'Caputo Pizza', price: 42, category: 'flour', image: '../img/flour/caputo-pizza.jpg', stock: 50, description: "Made from top-quality soft wheat flour that is additive free and all-natural, it is milled slowly for optimal water absorption and superior yield. Its high protein and gluten content result in a consistent, long rise dough. To make an award-winning dough, mix this flour with neapolitan yeast, water, and salt and knead by hand or with a mixer on low-speed. Then, once your toppings are in place, cook by a wood fired, gas, or electric oven at 700 - 1000 degrees Fahrenheit for no longer than 90 seconds to achieve the classically delicious neapolitan crust.", detail: '55lb'},
    {id: 's1', name: 'Dexter-Russell Traditional', price: 13, category: 'scrapers', image: '../img/scrapers/dexterrussel-traditional.jpg', stock: 14, description: "Crafted from perforated 3003 aluminum, this pan is ideal for restaurants or bakeries that want to offer freshly baked bread daily. Add this pan to your establishment to get a reliable product at a price that won't break your budget.", detail: 'Medidas aproximadas: 8x3"'},
    {id: 's2', name: 'Ateco Straight Edge Plastic', price: 1, category: 'scrapers', image: '../img/scrapers/ateco-plastic.jpg', stock: 10, description: "Designed with consistency and convenience in mind, this pan saves time by allowing you to bake up to four uniform bread loaves simultaneously, helping you streamline any commercial operation. Each individual pan yields a 1 lb. bread loaf for a total of four consistent results every time.", detail: 'Medidas aproximadas: 5x3"'},
    {id: 's3', name: 'Mercer Culinary Millennia', price: 9, category: 'scrapers', image: '../img/scrapers/mercerculinary-millenia.jpg', stock: 5, description: "This Pullman pan is ideal for making loaves of bread with a fine compact crumb. This type of bread is generally used for sandwiches as it tends to have a light thin crust and perfectly square shape.", detail: 'Medidas aproximadas: 6x5"'},
    {id: 's4', name: 'Stainless Steel Dough Cutter', price: 4, category: 'scrapers', image: '../img/scrapers/stainless.jpg', stock: 15, description: "This high quality 1 lb. loaf pan is made of durable 24 gauge aluminized steel for excellent heat conduction. Its heavy-duty design combines the strength of steel with the conduction properties of aluminum, making it more than able to stand up to heavy daily use baking bread in bakeries and commercial kitchens.", detail: 'Medidas aproximadas: 5x4"'},
    {id: 's5', name: 'Fox Run Gray Plastic', price: 6, category: 'scrapers', image: '../img/scrapers/foxrun-plastic.jpg', stock: 20, description: "From oven to table, the Choice wide rim pizza pan offers a lightweight, easy-to-carry baking and serving alternative for pizzas or various side dishes. Whether baking in a conveyor or deck oven, you'll find that the overall utility of the pan is optimal for more than just pizza, as it is equally suitable for oven-to-table appetizers like nachos and breadsticks or other entrees like pub sandwiches.", detail: 'Medidas aproximadas: 4x4"'},
    {id: 'p1', name: 'Bakers Mark - Glazzed Alum 5 Baguette', price: 35, category: 'bakingpan', image: '../img/bakingpan/barkers-alumbaguette.jpg', stock: 10, description: "This scraper is designed to make prepwork a breeze in your commercial kitchen. It features a handle made of polished rosewood for comfort and longevity. Large brass compression rivets ensure the handle is secure and provides durability to this useful tool.", detail: 'Medidas aproximadas: 26x18"'},
    {id: 'p2', name: 'Bakers Mark - Glazzed Alum 4 Bread Loaf', price: 40, category: 'bakingpan', image: '../img/bakingpan/barkers-alum4loaf.jpg', stock: 12, description: "You can use this bowl scraper to scrape clean batter, icing, or dough from the mixing bowl, so you get more of your product into the baking pan and less in your dish water. You can also use the scraper to evenly distribute icing over cakes, or even cut dough if you're in a pinch.", detail: 'Medidas aproximadas: 21x9x3"'},
    {id: 'p3', name: 'Bakers Mark - Glazzed Alum Pullman', price: 14, category: 'bakingpan', image: '../img/bakingpan/barkers-alumloaf.jpg', stock: 17, description: "Featuring a high carbon, precision ground, no-stain stainless steel blade, this bench scraper has the perfect combination of sturdiness and flexibility for cutting dough for pastries, pizzas, and stromboli. It can also be used to scrape sticky remnants from your countertop or work station.", detail: 'Medidas aproximadas: 16x4x4"'},
    {id: 'p4', name: 'Bakers Mark - Glazzed Alum Bread Load', price: 8, category: 'bakingpan', image: '../img/bakingpan/bakers-loaf2.jpg', stock: 21, description: "Not only can it slice through dough to create perfect portions, but it can also help scrape up any leftover dough. as well. With an all stainless steel construction, this dough scraper is built to last, easily gliding on flat surfaces to divide or scrape dough. You'll love how its flexible, satin finish blade is effortlessly maneuvered around your workspace by its easy-to-grip, round handle!", detail: 'Medidas aproximadas: 9x4x3"'},
    {id: 'p5', name: 'Choice Wide Rim Pizza', price: 4, category: 'bakingpan', image: '../img/bakingpan/choice-alumpizza.jpg', stock: 27, description: "Made from a durable yet flexible plastic, this dough cutter makes it easy to work through doughs for clean cutting. Its curved silicone handle fits perfectly along the wall of your mixing bowl to scrape pieces of dough off so you don't waste any product. You can also use it at the end of the day to help scrape up crusted-on foods for easy cleanup. The scraper's green and gray color also makes it easy to locate or to identify among your other baking utensils.", detail: 'Medidas aproximadas: 16"'}
]

export const getProducts = (categoryId) => {
    return new Promise (resolve => {
        setTimeout(() => {
            resolve(categoryId ? products.filter(prod => prod.category === categoryId) : products)
        }, 500)
    })
}

const categories = [
    {id: 'banneton', description:"Banneton's"},
    {id: 'flour', description: 'Flour'},
    {id: 'scrapers', description: 'Scrapers'},
    {id: 'bakingpan', description: "Baking Pan's"}
]

export const getCategories = () => {
    return new Promise ( resolve => {
        setTimeout(() => {
            resolve(categories)
        }, 500)
    })
}

export const getProductsById = (id) => {
    return new Promise (resolve => {
        setTimeout(() => {
            resolve(products.find(prod => prod.id === id))
        }, 300)
    })
}